AB2D-6108 TIBQ: ab2d-sample-client-bash
CMSgov/ab2d-sample-client-bash pull request #16
Opened 2024-07-19 17:53 UTC by smirnovaae

## 🎫 Ticket

https://jira.cms.gov/browse/AB2D-6108

## 🛠 Changes

- Added _until parameter to bootstrap.sh and start-job.sh

## ℹ️ Context

Currently, AB2D API only accepts _since as a date parameter. The goal is for AB2D to be able to support the use case where a PDP could run jobs with time interval based queries so that they could download their data in batches. To achieve that, we will add a _until parameter to define the upper ceiling of the date range. 

Both the since and _until parameter will be applied to the lastupdated_Date. 

## 🧪 Validation

<img width="1176" alt="Screenshot 2024-07-18 at 2 50 50 PM" src="https://github.com/user-attachments/assets/2bfbcaa3-ad8f-4bf1-82ea-b21c06be2aae">

2024-07-19 18:00 UTC, coilysiren approved these changes
👍!

2024-07-19 18:09 UTC, Sadibhatla approved these changes

2024-07-30 19:04 UTC, phamjennifer commented on README.md
> +2. Using credentials in `my-orgs-creds.base64`
"Use" in present tense to match the rest of the instructions for consistency

2024-07-30 19:05 UTC, phamjennifer commented on README.md
> +Examples:
There is a space between the other headings and their contents. Do we want to do the same here for consistency? E.g., Files, Limitations, Example

2024-07-30 19:05 UTC, phamjennifer commented on README.md
> +ISO date time format of `yyyy-MM-dd'T'HH:mm:ss.SSSXXX+/-ZZ:ZZ`
Can we add a period at the end of this sentence?

2024-07-30 19:13 UTC, phamjennifer requested changes
I left some single comments but wanted to discuss the example section. Would a revision like this work? Also, confirming we want the example to describe date ranges using both parameters, not just the until parameter alone. 

Example scenario: 

1. Start a job request in (? I'm okay with "running against" too if it's a terminology thing. Whichever is more accurate) production.
2. Use credentials in `my-orgs-creds.base64.`
3. Save all results for this job to the directory /opt/foo.
4. Filter for claims data updated between April 1st, 2020 at 9:00 AM Eastern Time and June 1st, 2020 at 9:00 AM Eastern Time by running the following command:
...

--------------

Member
@[phamjennifer](https://github.com/phamjennifer) phamjennifer 2 minutes ago
"Use" in present tense to match the rest of the instructions for consistency

@phamjennifer	Reply...
4. Save all results for this job to the directory /opt/foo
5. And only get data after April 1st 2020 at 9:00 AM Eastern Time and before June 1st 2020 at 9:00 AM Eastern Time

2024-09-05 16:44 UTC, Rwolfe-Nava commented
Added some error handling so that the script will exit if a job fails to export rather than continuing to try and monitor / download results.

2024-10-18 17:53 UTC, phamjennifer approved these changes

2024-10-21 16:35 UTC, merged